players_data = [
    {
        "Spieler": "Robin Koch",
        "Land": "de GER",
        "Pos": "DF",
        "Alt": "28-078",
        "GS": "5",
        "Startelf": "5",
        "Min.": "450",
        "90": "5.0",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "1",
        "Rot": "0",
        "xG": "0.1",
        "npxG": "0.1",
        "xAG": "0.0",
        "npxG+xAG": "0,1",
        "PrgC": "0",
        "PrgP": "17",
        "PrgR": "1",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,03",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,03",
        "npxG_per_90": "0,03",
        "npxG+xAG_per_90": "0,03",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Rasmus Kristensen",
        "Land": "dk DEN",
        "Pos": "DF,MF",
        "Alt": "27-084",
        "GS": "5",
        "Startelf": "5",
        "Min.": "450",
        "90": "5.0",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.3",
        "npxG+xAG": "0,3",
        "PrgC": "10",
        "PrgP": "25",
        "PrgR": "13",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,01",
        "xAG_per_90": "0,05",
        "xG+xAG_per_90": "0,06",
        "npxG_per_90": "0,01",
        "npxG+xAG_per_90": "0,06",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Tuta",
        "Land": "br BRA",
        "Pos": "DF,MF",
        "Alt": "25-091",
        "GS": "5",
        "Startelf": "5",
        "Min.": "449",
        "90": "5.0",
        "Tor": "1",
        "Vor": "1",
        "T+V": "2",
        "T-Elf": "1",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.2",
        "npxG": "0.2",
        "xAG": "0.1",
        "npxG+xAG": "0,3",
        "PrgC": "2",
        "PrgP": "10",
        "PrgR": "2",
        "Tor_per_90": "0,20",
        "Vor_per_90": "0,20",
        "T+V_per_90": "0,40",
        "T-Elf_per_90": "0,20",
        "T+V-Elf_per_90": "0,40",
        "xG_per_90": "0,05",
        "xAG_per_90": "0,01",
        "xG+xAG_per_90": "0,06",
        "npxG_per_90": "0,05",
        "npxG+xAG_per_90": "0,06",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Hugo Larsson",
        "Land": "se SWE",
        "Pos": "MF",
        "Alt": "20-098",
        "GS": "5",
        "Startelf": "5",
        "Min.": "433",
        "90": "4.8",
        "Tor": "2",
        "Vor": "0",
        "T+V": "2",
        "T-Elf": "2",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "1",
        "Rot": "0",
        "xG": "1.8",
        "npxG": "1.8",
        "xAG": "0.2",
        "npxG+xAG": "1,9",
        "PrgC": "2",
        "PrgP": "19",
        "PrgR": "4",
        "Tor_per_90": "0,42",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,42",
        "T-Elf_per_90": "0,42",
        "T+V-Elf_per_90": "0,42",
        "xG_per_90": "0,36",
        "xAG_per_90": "0,03",
        "xG+xAG_per_90": "0,40",
        "npxG_per_90": "0,36",
        "npxG+xAG_per_90": "0,40",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Arthur Theate",
        "Land": "be BEL",
        "Pos": "DF",
        "Alt": "24-131",
        "GS": "5",
        "Startelf": "5",
        "Min.": "428",
        "90": "4.8",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "1",
        "Rot": "0",
        "xG": "0.1",
        "npxG": "0.1",
        "xAG": "0.0",
        "npxG+xAG": "0,1",
        "PrgC": "5",
        "PrgP": "16",
        "PrgR": "4",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,03",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,03",
        "npxG_per_90": "0,03",
        "npxG+xAG_per_90": "0,03",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Omar Marmoush",
        "Land": "eg EGY",
        "Pos": "FW,MF",
        "Alt": "25-239",
        "GS": "5",
        "Startelf": "5",
        "Min.": "411",
        "90": "4.6",
        "Tor": "6",
        "Vor": "3",
        "T+V": "9",
        "T-Elf": "5",
        "Elf": "1",
        "VeElf": "1",
        "Gelb": "0",
        "Rot": "0",
        "xG": "3.5",
        "npxG": "2.7",
        "xAG": "3.7",
        "npxG+xAG": "6,4",
        "PrgC": "23",
        "PrgP": "11",
        "PrgR": "33",
        "Tor_per_90": "1,31",
        "Vor_per_90": "0,66",
        "T+V_per_90": "1,97",
        "T-Elf_per_90": "1,09",
        "T+V-Elf_per_90": "1,75",
        "xG_per_90": "0,77",
        "xAG_per_90": "0,82",
        "xG+xAG_per_90": "1,59",
        "npxG_per_90": "0,60",
        "npxG+xAG_per_90": "1,41",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Ellyes Skhiri",
        "Land": "tn TUN",
        "Pos": "MF",
        "Alt": "29-146",
        "GS": "5",
        "Startelf": "4",
        "Min.": "365",
        "90": "4.1",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "2",
        "Rot": "0",
        "xG": "0.1",
        "npxG": "0.1",
        "xAG": "0.1",
        "npxG+xAG": "0,1",
        "PrgC": "1",
        "PrgP": "11",
        "PrgR": "3",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,01",
        "xAG_per_90": "0,02",
        "xG+xAG_per_90": "0,03",
        "npxG_per_90": "0,01",
        "npxG+xAG_per_90": "0,03",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Hugo Ekitike",
        "Land": "fr FRA",
        "Pos": "FW",
        "Alt": "22-105",
        "GS": "4",
        "Startelf": "4",
        "Min.": "290",
        "90": "3.2",
        "Tor": "1",
        "Vor": "2",
        "T+V": "3",
        "T-Elf": "1",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "2.8",
        "npxG": "2.8",
        "xAG": "1.8",
        "npxG+xAG": "4,6",
        "PrgC": "14",
        "PrgP": "7",
        "PrgR": "23",
        "Tor_per_90": "0,31",
        "Vor_per_90": "0,62",
        "T+V_per_90": "0,93",
        "T-Elf_per_90": "0,31",
        "T+V-Elf_per_90": "0,93",
        "xG_per_90": "0,85",
        "xAG_per_90": "0,56",
        "xG+xAG_per_90": "1,42",
        "npxG_per_90": "0,85",
        "npxG+xAG_per_90": "1,42",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Fares Chaïbi",
        "Land": "dz ALG",
        "Pos": "FW,MF",
        "Alt": "21-310",
        "GS": "5",
        "Startelf": "3",
        "Min.": "282",
        "90": "3.1",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "1",
        "Gelb": "0",
        "Rot": "0",
        "xG": "1.8",
        "npxG": "1.8",
        "xAG": "0.5",
        "npxG+xAG": "2,2",
        "PrgC": "10",
        "PrgP": "15",
        "PrgR": "22",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,56",
        "xAG_per_90": "0,14",
        "xG+xAG_per_90": "0,70",
        "npxG_per_90": "0,56",
        "npxG+xAG_per_90": "0,70",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Kevin Trapp",
        "Land": "de GER",
        "Pos": "TW",
        "Alt": "34-087",
        "GS": "3",
        "Startelf": "3",
        "Min.": "225",
        "90": "2.5",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "0",
        "PrgP": "0",
        "PrgR": "0",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Mario Götze",
        "Land": "de GER",
        "Pos": "FW,MF",
        "Alt": "32-122",
        "GS": "4",
        "Startelf": "3",
        "Min.": "222",
        "90": "2.5",
        "Tor": "0",
        "Vor": "1",
        "T+V": "1",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.1",
        "npxG": "0.1",
        "xAG": "0.3",
        "npxG+xAG": "0,4",
        "PrgC": "6",
        "PrgP": "9",
        "PrgR": "10",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,41",
        "T+V_per_90": "0,41",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,41",
        "xG_per_90": "0,05",
        "xAG_per_90": "0,12",
        "xG+xAG_per_90": "0,17",
        "npxG_per_90": "0,05",
        "npxG+xAG_per_90": "0,17",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Kauã Santos",
        "Land": "br BRA",
        "Pos": "TW",
        "Alt": "21-175",
        "GS": "3",
        "Startelf": "2",
        "Min.": "225",
        "90": "2.5",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "0",
        "PrgP": "0",
        "PrgR": "0",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Niels Nkounkou",
        "Land": "fr FRA",
        "Pos": "MF,DF",
        "Alt": "23-337",
        "GS": "4",
        "Startelf": "2",
        "Min.": "173",
        "90": "1.9",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "1.1",
        "npxG+xAG": "1,1",
        "PrgC": "10",
        "PrgP": "5",
        "PrgR": "9",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,02",
        "xAG_per_90": "0,58",
        "xG+xAG_per_90": "0,60",
        "npxG_per_90": "0,02",
        "npxG+xAG_per_90": "0,60",
        "Spiele": "Spiele"
    },

    {
        "Spieler": "Igor Matanovic",
        "Land": "hr CRO",
        "Pos": "FW",
        "Alt": "21-186",
        "GS": "5",
        "Startelf": "1",
        "Min.": "145",
        "90": "1.6",
        "Tor": "1",
        "Vor": "0",
        "T+V": "1",
        "T-Elf": "1",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.7",
        "npxG": "0.7",
        "xAG": "0.0",
        "npxG+xAG": "0,8",
        "PrgC": "2",
        "PrgP": "2",
        "PrgR": "12",
        "Tor_per_90": "0,62",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,62",
        "T-Elf_per_90": "0,62",
        "T+V-Elf_per_90": "0,62",
        "xG_per_90": "0,45",
        "xAG_per_90": "0,02",
        "xG+xAG_per_90": "0,47",
        "npxG_per_90": "0,45",
        "npxG+xAG_per_90": "0,47",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Ansgar Knauff",
        "Land": "de GER",
        "Pos": "MF,FW",
        "Alt": "22-267",
        "GS": "5",
        "Startelf": "1",
        "Min.": "134",
        "90": "1.5",
        "Tor": "0",
        "Vor": "1",
        "T+V": "1",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.1",
        "npxG": "0.1",
        "xAG": "0.8",
        "npxG+xAG": "0,8",
        "PrgC": "3",
        "PrgP": "7",
        "PrgR": "11",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,67",
        "T+V_per_90": "0,67",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,67",
        "xG_per_90": "0,05",
        "xAG_per_90": "0,52",
        "xG+xAG_per_90": "0,57",
        "npxG_per_90": "0,05",
        "npxG+xAG_per_90": "0,57",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Junior Dina Ebimbe",
        "Land": "fr FRA",
        "Pos": "FW,MF",
        "Alt": "23-317",
        "GS": "2",
        "Startelf": "1",
        "Min.": "88",
        "90": "1.0",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.1",
        "npxG": "0.1",
        "xAG": "0.6",
        "npxG+xAG": "0,7",
        "PrgC": "0",
        "PrgP": "1",
        "PrgR": "10",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,11",
        "xAG_per_90": "0,60",
        "xG+xAG_per_90": "0,71",
        "npxG_per_90": "0,11",
        "npxG+xAG_per_90": "0,71",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Aurele Amenda",
        "Land": "ch SUI",
        "Pos": "DF",
        "Alt": "21-064",
        "GS": "2",
        "Startelf": "1",
        "Min.": "51",
        "90": "0.6",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "1",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "1",
        "PrgP": "1",
        "PrgR": "1",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Mahmoud Dahoud",
        "Land": "de GER",
        "Pos": "MF",
        "Alt": "28-276",
        "GS": "2",
        "Startelf": "0",
        "Min.": "51",
        "90": "0.6",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "0",
        "PrgP": "2",
        "PrgR": "0",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,03",
        "xG+xAG_per_90": "0,03",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,03",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Can Uzun",
        "Land": "tr TUR",
        "Pos": "FW,MF",
        "Alt": "18-327",
        "GS": "3",
        "Startelf": "0",
        "Min.": "50",
        "90": "0.6",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "0",
        "PrgP": "2",
        "PrgR": "1",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Oscar Højlund",
        "Land": "dk DEN",
        "Pos": "MF",
        "Alt": "19-273",
        "GS": "1",
        "Startelf": "0",
        "Min.": "14",
        "90": "0.2",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "1",
        "PrgP": "0",
        "PrgR": "1",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Jean Mattéo Bahoya",
        "Land": "fr FRA",
        "Pos": "MF",
        "Alt": "19-149",
        "GS": "1",
        "Startelf": "0",
        "Min.": "13",
        "90": "0.1",
        "Tor": "0",
        "Vor": "1",
        "T+V": "1",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.3",
        "npxG+xAG": "0,3",
        "PrgC": "1",
        "PrgP": "1",
        "PrgR": "1",
        "Tor_per_90": "0,00",
        "Vor_per_90": "6,92",
        "T+V_per_90": "6,92",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "6,92",
        "xG_per_90": "0,00",
        "xAG_per_90": "2,34",
        "xG+xAG_per_90": "2,34",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "2,34",
        "Spiele": "Spiele"
    },
    {
        "Spieler": "Nnamdi Collins",
        "Land": "de GER",
        "Pos": "DF",
        "Alt": "20-267",
        "GS": "1",
        "Startelf": "0",
        "Min.": "1",
        "90": "0.0",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "0",
        "PrgP": "0",
        "PrgR": "0",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    },
{
        "Spieler": "Nnamdi Collins",
        "Land": "de GER",
        "Pos": "DF",
        "Alt": "20-267",
        "GS": "1",
        "Startelf": "0",
        "Min.": "1",
        "90": "0.0",
        "Tor": "0",
        "Vor": "0",
        "T+V": "0",
        "T-Elf": "0",
        "Elf": "0",
        "VeElf": "0",
        "Gelb": "0",
        "Rot": "0",
        "xG": "0.0",
        "npxG": "0.0",
        "xAG": "0.0",
        "npxG+xAG": "0,0",
        "PrgC": "0",
        "PrgP": "0",
        "PrgR": "0",
        "Tor_per_90": "0,00",
        "Vor_per_90": "0,00",
        "T+V_per_90": "0,00",
        "T-Elf_per_90": "0,00",
        "T+V-Elf_per_90": "0,00",
        "xG_per_90": "0,00",
        "xAG_per_90": "0,00",
        "xG+xAG_per_90": "0,00",
        "npxG_per_90": "0,00",
        "npxG+xAG_per_90": "0,00",
        "Spiele": "Spiele"
    }
]


